MovieStoreApp/MovieStoreApp.WebMVC/Models/ErrorViewModel.cs
namespace MovieStoreApp.WebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Models/MovieViewModel.cs
namespace MovieStoreApp.WebMVC.Models
{
    public class MovieViewModel
    {
        
    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Component/LatestMovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;
namespace MovieStoreApp.WebMVC.Component
{
    public class LatestMovieViewComponent : ViewComponent
    {
        IMovieServiceAsync movieService;
        public LatestMovieViewComponent(IMovieServiceAsync ser)
        {
            movieService = ser;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await movieService.GetTop3LatestMoviesAsync();
            return View("latestmovie", result);
        }
    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Component/TopMovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;

namespace MovieStoreApp.WebMVC.Component
{
    public class TopMovieViewComponent : ViewComponent
    {
        IMovieServiceAsync movieService;
        public TopMovieViewComponent(IMovieServiceAsync ser)
        {
            movieService = ser;
        }

        public async Task<IViewComponentResult> InvokeAsync(int movieId)
        {

            var result = await movieService.GetTop10RevenueMoviesAsync();

            return View(result);
        }
    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.WebMVC.Models;
using System.Diagnostics;

namespace MovieStoreApp.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieStoreApp.WebMVC.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;
using MovieStoreApp.WebMVC.Models;
namespace MovieStoreApp.WebMVC.Controllers
{
    public class MovieController : Controller
    {
        IMovieServiceAsync movieService;
        IMovieCastService movieCastService;
        public MovieController(IMovieServiceAsync ser, IMovieCastService castService)
        {
            movieService = ser;
            movieCastService = castService;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "All Movies";

            //var result =await movieService.GetTop10RevenueMoviesAsync();

            return View();
        }

        public async Task<IActionResult> Detail(int movieId)
        { 
            var result = await movieService.GetByIdAsync(movieId);
            result.MovieCasts = await movieCastService.GetAllByMovieId(movieId);

            return View(result);
        }

    }
}

MovieStoreApp/MovieStoreApp.WebMVC/Views/Home/Index.cshtml
@{
    
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MovieStoreApp/MovieStoreApp.WebMVC/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<h1>This is login page</h1>
Razor view 
its extensiton is

cshtml
cs + html


Razor View Engine:- it is a piece of code which will convert the C# code of the razor
view to an html code.

@{
    int a = 20;
    int b = 30;
    int c = a + b;
    <h3>Sum = @c </h3>
    <table border="1">
    @for (int i = 0; i < 10; i++)
    {
        <tr>
        <td  >@i</td>
        </tr>
    }
    </table>

}


Layout
header--- menu, logo, login/signup

Content:- it will be keep changing

footer-- rights, social media icon

Shared views

section RenderBody()

MovieStoreApp/MovieStoreApp.WebMVC/Views/Movie/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*<div class="row">
<form  method="post">
    <div class="mb-3">
    <label asp-for="Title"></label>
    <input asp-for="Title" class="form-control"/>
    </div>

    <div class="mb-3">
    <label asp-for="PosterUrl"></label>
    <input asp-for="PosterUrl" class="form-control"/>
    </div>
    <div class="mb-3">
    <label asp-for="ReleaseDate"></label>
    <input asp-for="ReleaseDate" class="form-control"/>
    </div>
    <div class="mb-3">
    <label asp-for="Duration"></label>
    <input asp-for="Duration" class="form-control"/>
    </div>
    <div class="mb-3">
    <label asp-for="Description"></label>
    <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <input type="submit" value="Add Movie" class="btn btn-primary"/>
</form>
</div>*@

MovieStoreApp/MovieStoreApp.WebMVC/Views/Movie/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MovieResponseModel
<div class="container">
    <h3 class="display-4">@Model.Title Detail</h3> <hr/>
    <div class="row">
        <div class="col-4">
            <img src="@Model.PosterUrl" />
        </div>
        <div class="col-8">
            <ul class="list-group">
                <li class="list-group-item">Title - @Model.Title</li>
                <li class="list-group-item">Tagline - @Model.Tagline</li>
                <li class="list-group-item">Runtime - @Model.Runtime | Budget - @Model.Budget</li>
                <li class="list-group-item">Description - @Model.Overview</li>
                <li class="list-group-item">Language - @Model.OriginalLanguage | Release On : @Model.ReleaseDate.ToShortDateString() </li>
            </ul>


            @foreach(var mcast in @Model.MovieCasts)
            {
                
            
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <img src="@mcast.Cast.ProfilePath" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@mcast.Cast.Name</h5>
                            <p class="card-text">@mcast.Cast.Gender</p>
                        </div>
                    </div>
                </div>
                <br />
            }
        </div>
    </div>
</div>

MovieStoreApp/MovieStoreApp.WebMVC/Views/Movie/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MovieResponseModel>;
<div class="row">
    <div class="col-9">
        <h4>
            @ViewBag.Title
        </h4>
    </div>
    <div class="col-3">
        <a asp-controller="Movie" asp-action ="Create">Add New Movie</a>
    </div>
</div>
<h2>Top Revenue Movies</h2>
@await Component.InvokeAsync("TopMovie")
<hr/>
<h2>Latest movies</h2>
@await Component.InvokeAsync("LatestMovie")

MovieStoreApp/MovieStoreApp.WebMVC/Views/Shared/Components/LatestMovie/latestmovie.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MovieResponseModel>

<div class="row">
    @foreach (var m in Model)
    {
       <partial name="_MovieCard" model="@m"></partial>
    }
</div>

MovieStoreApp/MovieStoreApp.WebMVC/Views/Shared/Components/TopMovie/default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<MovieResponseModel>;
<div class="row">
    @foreach (var m in Model)
    {
        <partial name="_MovieCard" model="@m"> </partial>
    }
</div>

MovieStoreApp/MovieStoreApp.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My MovieStore App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieStoreApp.WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">Movie Database</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">All Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
          @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieStoreApp.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
        
</body>
</html>

MovieStoreApp/MovieStoreApp.WebMVC/Views/Shared/_MovieCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model MovieResponseModel;
<div class="col-4 mb-4">
            <div class="card" style="width: 18rem;">
                <img src="@Model.PosterUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Overview</p>
                    <a target="_blank" asp-controller="movie" asp-action="detail" asp-route-movieId="@Model.Id" class="btn btn-primary">Show Details</a>
                </div>
            </div>
        </div>
        <br />